tags:
  - ml_endpoint
info:
  title: Prediction open api spec
  version: 1.0.0
openapi: 3.0.2
parameters:
- in: "body"
  name: "data"
  description: "List of feature records."
  required: true
  schema:
    $ref: "#/definitions/prediction_input"
responses:
  200:
    description: "List of predictions"
    name: predictions
    schema:
      $ref: "#/definitions/predictions"

definitions:
  prediction_input:
      properties:
        data:
          items:
            properties:
              petal_length:
                format: float
                nullable: false
                type: number
              petal_width:
                format: float
                nullable: false
                type: number
              sepal_length:
                format: float
                nullable: false
                type: number
              sepal_width:
                format: float
                nullable: false
                type: number
          type: array
      required:
      - data
      type: object
  predictions:
      properties:
        predictions:
          items:
            format: float
            nullable: false
            type: string
      type: array




